version: "3.9"

volumes:
  banner_db:
  banner_rabbitmq:

services:
  db:
    image: library/postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - banner_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "${AMQP_PORT}:5672"
      - "${AMQP_UI_PORT}:15672"
    volumes:
      - banner_rabbitmq:/var/lib/rabbitmq/
