name: Otus homework banner rotator tests

on:
  push:
    branches:
      - *

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.*

      - name: Check out code
        uses: actions/checkout@v3

      - name: make build-binary
        run: make build-binary
        working-directory: ${{ env.BRANCH }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.*

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.*

      - name: Check out code
        uses: actions/checkout@v3

      - name: make test
        run: make test
        working-directory: ${{ env.BRANCH }}

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.*

      - name: Check out code
        uses: actions/checkout@v3

      - name: make integration-tests
        run: make integration-tests
        working-directory: ${{ env.BRANCH }}
